apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: inventory-service